In [ ]:
import pandas as pd

In [13]:
df = pd.read_csv("Concrete Compressive Strength.csv")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1030 entries, 0 to 1029
Data columns (total 9 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Cement                          1030 non-null   float64
 1   Blast Furnace Slag              1030 non-null   float64
 2   Fly Ash                         1030 non-null   float64
 3   Water                           1030 non-null   float64
 4   Superplasticizer                1030 non-null   float64
 5   Coarse Aggregate                1030 non-null   float64
 6   Fine Aggregate                  1030 non-null   float64
 7   Age (day)                       1030 non-null   int64
 8   Concrete compressive strength   1030 non-null   float64
dtypes: float64(8), int64(1)
memory usage: 72.6 KB

In [14]:
df.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age (day),Concrete compressive strength
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28,79.986111
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28,61.887366
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270,40.269535
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365,41.052780
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360,44.296075

In [15]:
df['Cement'].nunique()

280

In [16]:
def cleaner(df):
    for col in df.columns:
        if df[col].isnull().any():
            if df[col].dtype=="object":
                df[col].fillna(df[col].mode()[0], inplace=True)
            else:
                df[col].fillna(df[col].mean(), inplace=True)
    return df

In [17]:
df = cleaner(df)

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1030 entries, 0 to 1029
Data columns (total 9 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Cement                          1030 non-null   float64
 1   Blast Furnace Slag              1030 non-null   float64
 2   Fly Ash                         1030 non-null   float64
 3   Water                           1030 non-null   float64
 4   Superplasticizer                1030 non-null   float64
 5   Coarse Aggregate                1030 non-null   float64
 6   Fine Aggregate                  1030 non-null   float64
 7   Age (day)                       1030 non-null   int64
 8   Concrete compressive strength   1030 non-null   float64
dtypes: float64(8), int64(1)
memory usage: 72.6 KB

In [19]:
def encodlash(df):
    from sklearn.preprocessing import LabelEncoder
    encoder = LabelEncoder()    
    for col in df.columns:
        if df[col].dtype=="object":
            if df[col].nunique()<=6:
                dummies = pd.get_dummies(df[col], prefix="col", dtype=int)
                df = pd.concat([df.drop(columns=col), dummies,], axis = 1)
            else:
                encoder = LabelEncoder()
                df[col] = encoder.fit_transform(df[col])
    return df

In [20]:
df = encodlash(df)

In [21]:
df.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age (day),Concrete compressive strength
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28,79.986111
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28,61.887366
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270,40.269535
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365,41.052780
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360,44.296075

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1030 entries, 0 to 1029
Data columns (total 9 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Cement                          1030 non-null   float64
 1   Blast Furnace Slag              1030 non-null   float64
 2   Fly Ash                         1030 non-null   float64
 3   Water                           1030 non-null   float64
 4   Superplasticizer                1030 non-null   float64
 5   Coarse Aggregate                1030 non-null   float64
 6   Fine Aggregate                  1030 non-null   float64
 7   Age (day)                       1030 non-null   int64
 8   Concrete compressive strength   1030 non-null   float64
dtypes: float64(8), int64(1)
memory usage: 72.6 KB

In [23]:
def scalinglash(df):
    from sklearn.preprocessing import StandardScaler
    standart_scaler = StandardScaler()
    num_col = df.select_dtypes(include=["float64", "int64"]).columns.drop("Cement")
    df[num_col]= standart_scaler.fit_transform(df[num_col])
    return df

In [24]:
df = scalinglash(df)

In [25]:
x = df.drop("Cement", axis=1)
y = df['Cement']

In [26]:
from sklearn.model_selection import train_test_split

In [27]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

# Algoritm Decision Tree Classifier

In [31]:
from sklearn.tree import DecisionTreeRegressor
model_tree = DecisionTreeRegressor()

In [32]:
model_tree

DecisionTreeRegressor()

In [33]:
model_tree.fit(x_train, y_train)

DecisionTreeRegressor()

In [34]:
y_pred = model_tree.predict(x_test)
y_pred

array([266.  , 362.6 , 389.9 , 362.6 , 145.4 , 276.  , 148.5 , 251.81,
       212.57, 393.  , 336.  , 238.2 , 318.8 , 239.6 , 173.54, 210.7 ,
       317.9 , 250.2 , 272.8 , 165.  , 155.  , 165.  , 295.71, 166.8 ,
       214.9 , 249.1 , 225.  , 313.3 , 213.5 , 339.  , 339.  , 393.  ,
       203.5 , 213.5 , 167.35, 220.8 , 212.52, 272.8 , 133.  , 297.16,
       300.  , 116.  , 200.  , 387.  , 229.97, 374.  , 397.  , 307.  ,
       302.  , 141.3 , 321.3 , 141.3 , 154.  , 181.9 , 446.  , 362.6 ,
       212.57, 252.  , 190.34, 252.5 , 272.8 , 520.  , 229.97, 425.  ,
       212.  , 164.6 , 252.  , 313.3 , 233.81, 251.37, 289.  , 183.9 ,
       236.  , 336.  , 149.  , 222.36, 342.  , 213.5 , 491.  , 139.6 ,
       139.6 , 388.6 , 333.  , 238.05, 332.5 , 362.6 , 141.9 , 262.  ,
       182.04, 229.97, 339.  , 401.8 , 190.68, 330.5 , 277.  , 190.  ,
       212.  , 213.72, 393.  , 307.  , 397.  , 287.3 , 237.5 , 382.  ,
       469.  , 238.1 , 173.54, 305.  , 213.5 , 284.  , 139.6 , 277.05,
       220.8 , 194.68, 359.  , 446.  , 350.  , 162.  , 218.23, 277.  ,
       155.  , 254.  , 213.5 , 350.  , 334.  , 182.04, 540.  , 425.  ,
       288.  , 261.  , 382.  , 277.05, 200.  , 439.  , 255.  , 332.5 ,
       331.  , 212.07, 290.35, 155.6 , 172.38, 322.2 , 173.54, 277.  ,
       314.  , 277.  , 153.  , 145.  , 133.  , 295.  , 277.05, 148.  ,
       387.  , 172.38, 168.88, 250.  , 299.8 , 540.  , 362.6 , 289.  ,
       198.6 , 375.  , 295.71, 380.  , 425.  , 359.  , 427.5 , 251.37,
       446.  , 251.81, 275.07, 157.  , 194.68, 326.  , 151.8 , 186.2 ,
       200.  , 277.05, 289.  , 339.  , 162.  , 148.  , 284.  , 350.  ,
       246.83, 342.  , 252.  , 218.85, 288.  , 310.  , 387.  , 172.38,
       190.34, 424.  , 254.  , 167.  , 213.5 , 148.  , 147.  , 238.2 ,
       277.19, 446.  , 255.  , 286.3 , 424.  , 339.  ])

In [35]:
from sklearn.metrics import  r2_score, mean_squared_error

In [37]:
score = r2_score(y_test, y_pred)
score

0.8562285006938648

# Algoritm Decisiton Tree Regressor

# Hyperparameter Grid Search CV bo`yicha

In [40]:
from sklearn.model_selection import GridSearchCV
dt_params={
    'max_depth':[3, 5, 10, None],    
    'min_samples_split':[2,5,10]
}

dt = DecisionTreeRegressor(random_state=42)
grid_dt = GridSearchCV(estimator=dt, param_grid=dt_params, cv=5, scoring='r2')
grid_dt.fit(x_train, y_train)
best_dt = grid_dt.best_estimator_

y_pred_dt = best_dt.predict(x_test)
print("Decision Tree Best Parameters:", grid_dt.best_params_)

Decision Tree Best Parameters: {'max_depth': 10, 'min_samples_split': 5}

In [41]:
score=r2_score(y_test,y_pred_dt)
score

0.8995376575180546

# Hyperparameter RandomisedSearchCV  bo`yicha

In [51]:
from sklearn.model_selection import RandomizedSearchCV
dt_param_dist = {
    'max_depth': [3, 5, 10, None],
    'min_samples_split': [2, 11]
}

dt_model = DecisionTreeRegressor(random_state=42)
dt_random = RandomizedSearchCV(model_tree, dt_param_dist, n_iter=10, cv=5, scoring='r2', random_state=42)
dt_random.fit(x_train, y_train)
dt_best = dt_random.best_estimator_
print("Best Decision Tree R2:", r2_score(y_test, dt_best.predict(x_test)))

c:\Users\Rasulbek_Ruzmetov\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\model_selection\_search.py:317: UserWarning: The total space of parameters 8 is smaller than n_iter=10. Running 8 iterations. For exhaustive searches, use GridSearchCV.
  warnings.warn(

Best Decision Tree R2: 0.913845590040721

#  Algoritm Random Forest Regressor bo`yicha

# Hyperparameter Grid Search CV bo`yicha

In [46]:
from sklearn.ensemble import RandomForestRegressor
rf_model=RandomForestRegressor()
from sklearn.model_selection import GridSearchCV
rf_params = {
    'n_estimators': [50, 100],
    'max_depth': [5, 10, None],
    'min_samples_split': [2, 5]
}

rf_model = RandomForestRegressor(random_state=42)
rf_grid = GridSearchCV(rf_model, rf_params, cv=5, scoring='r2')
rf_grid.fit(x_train, y_train)
rf_best = rf_grid.best_estimator_
print("Best Random Forest R2:", r2_score(y_test, rf_best.predict(x_test)))

Best Random Forest R2: 0.9576493810623468

# Hyperparameter Randomised Regressor CV bo`yicha

In [50]:
from sklearn.ensemble import RandomForestRegressor
rf_model=RandomForestRegressor()
from sklearn.model_selection import RandomizedSearchCV
rf_param_dist = {
    'n_estimators': [50, 200],
    'max_depth': [5, 10, None],
    'min_samples_split': [2, 11]
}

rf_model = RandomForestRegressor(random_state=42)
rf_random = RandomizedSearchCV(rf_model, rf_param_dist, n_iter=10, cv=5, scoring='r2', random_state=42)
rf_random.fit(x_train, y_train)
rf_best = rf_random.best_estimator_
print("Best Random Forest R2:", r2_score(y_test, rf_best.predict(x_test)))

Best Random Forest R2: 0.9577134196681578